-- Impactrack - Seed de 15 empresas fictícias
-- Execute após o schema.sql no banco "impactrack"

USE impactrack;

INSERT INTO empresa (
    name, description, logo, esg_score, environmental, social, governance,
    category, highlighted, criteria_emissions, criteria_renewable, criteria_diversity,
    criteria_labor, criteria_transparency, alerts_json
) VALUES
(
    'EcoEnergia Brasil',
    'Empresa de energia renovável focada em solar e eólica. Operações em 12 estados com meta de carbono neutro até 2030.',
    'https://cdn.example.com/logos/ecoenergia.png',
    78, 85, 72, 77,
    'Energia',
    1,
    'Redução de 34% nas emissões escopo 1 e 2 em 2024',
    '85% da matriz energética de fontes renováveis',
    '40% de mulheres em cargos de liderança',
    'Programa de capacitação para 2.000 colaboradores/ano',
    'Relatório integrado GRI e SASB publicados anualmente',
    '["Alerta: prazo para meta de redução 2025 em revisão"]'
),
(
    'TechVerde Soluções',
    'Software e consultoria em sustentabilidade para médias e grandes empresas. Plataforma de monitoramento ESG.',
    'https://cdn.example.com/logos/techverde.png',
    82, 70, 88, 88,
    'Tecnologia',
    1,
    'Compensação de 100% das emissões de datacenter',
    'Energia contratada 100% renovável desde 2023',
    'Política de inclusão LGBTQIA+ e equidade de gênero',
    'Home office flexível e benefícios ampliados',
    'Divulgação trimestral de métricas ESG no site',
    '[]'
),
(
    'AgroSustentável S.A.',
    'Agronegócio com foco em agricultura regenerativa e rastreabilidade. Soja e milho com certificações internacionais.',
    'https://cdn.example.com/logos/agrosustentavel.png',
    65, 62, 68, 65,
    'Agronegócio',
    0,
    'Inventário de GEE em 100% das fazendas',
    'Uso de biodigestores em unidades selecionadas',
    'Programa de formação para comunidades do entorno',
    'Cumprimento integral da NR-31 e convenções OIT',
    'Relatório de sustentabilidade auditado externamente',
    '["Verificação de fornecedores indiretos em andamento"]'
),
(
    'MobiliCorp Logística',
    'Logística e transporte de cargas. Frota em transição para veículos elétricos e uso de biocombustíveis.',
    'https://cdn.example.com/logos/mobilicorp.png',
    58, 52, 61, 61,
    'Logística',
    0,
    'Meta de redução 25% até 2027 vs. baseline 2022',
    'Testes com HVO e biodiesel em rotas regionais',
    'Diversidade em 35% dos cargos operacionais',
    'Acordos coletivos e plano de carreira formalizado',
    'Indicadores de segurança publicados mensalmente',
    '["Incidentes de segurança acima da meta no último trimestre"]'
),
(
    'FarmaVida Indústria',
    'Indústria farmacêutica com foco em medicamentos genéricos e acesso à saúde. Pesquisa em doenças negligenciadas.',
    'https://cdn.example.com/logos/farmavida.png',
    74, 68, 82, 72,
    'Saúde',
    1,
    'Science Based Targets em definição',
    'Eficiência energética em todas as plantas',
    'Programa de doação de medicamentos e acesso',
    'Salário acima da média do setor; benefícios amplos',
    'Transparência em preços e ensaios clínicos',
    '[]'
),
(
    'ConstruMais Engenharia',
    'Construtora com atuação em obras sustentáveis. Certificações LEED e uso de materiais de baixo impacto.',
    'https://cdn.example.com/logos/construmais.png',
    61, 64, 58, 61,
    'Construção',
    0,
    'Uso de concreto de baixo carbono em projetos piloto',
    'Energia solar em canteiros de obra',
    'Capacitação e formalização de mão de obra',
    'Canal de denúncias e auditorias de subcontratados',
    'Relatório anual de sustentabilidade',
    '["Reclamações trabalhistas em análise"]'
),
(
    'RetailConsciente',
    'Varejo de moda e lifestyle com compromisso de rastreabilidade e algodão sustentável. Lojas em 8 capitais.',
    'https://cdn.example.com/logos/retailconsciente.png',
    69, 66, 72, 69,
    'Varejo',
    0,
    'Inventário de carbono da cadeia em elaboração',
    'Linhas com materiais reciclados e certificados',
    '50% de mulheres em cargos gerenciais',
    'Código de conduta para fornecedores auditado',
    'Listagem de fornecedores tier 1 no site',
    '[]'
),
(
    'FinançaVerde Banco',
    'Instituição financeira com linha de crédito verde e fundos de investimento ESG. Foco em impacto socioambiental.',
    'https://cdn.example.com/logos/financaverde.png',
    80, 72, 78, 90,
    'Financeiro',
    1,
    'Carbon footprint das operações neutralizado',
    'Energia 100% renovável nas agências',
    'Política de diversidade e inclusão publicada',
    'Remuneração atrelada a metas ESG para executivos',
    'Relatório anual ESG e integrado; taxonomia verde',
    '[]'
),
(
    'AlimentaBem Foods',
    'Indústria de alimentos com foco em produtos orgânicos e plant-based. Redução de plástico e embalagens recicláveis.',
    'https://cdn.example.com/logos/alimentabem.png',
    71, 72, 70, 71,
    'Alimentos',
    0,
    'Redução de 20% emissões por tonelada produzida',
    'Parte das unidades com energia solar',
    'Programa de alimentação para comunidades',
    'Rastreabilidade de fornecedores agrícolas',
    'Declaração de ingredientes e origem no produto',
    '["Não conformidade em auditoria de fornecedor em 2024"]'
),
(
    'AutoElétrica Mobilidade',
    'Montadora de veículos elétricos e híbridos. Investimento em baterias e infraestrutura de recarga.',
    'https://cdn.example.com/logos/autoeletrica.png',
    76, 88, 68, 72,
    'Automotivo',
    1,
    'Produto principal zero emissão direta; meta escopo 3',
    'Foco em eletrificação e reciclagem de baterias',
    'Parcerias com universidades para formação',
    'Acordos sindicais e segurança no trabalho',
    'Relatório de ciclo de vida dos veículos',
    '[]'
),
(
    'ÁguaPura Saneamento',
    'Concessionária de água e esgoto. Investimentos em perdas, reuso e tratamento de efluentes.',
    'https://cdn.example.com/logos/aguapura.png',
    73, 80, 70, 69,
    'Saneamento',
    0,
    'Redução de emissões em estações de tratamento',
    'Energia renovável em parte das estações',
    'Programas em comunidades de baixa renda',
    'Conformidade com normas trabalhistas e SST',
    'Indicadores de qualidade da água públicos',
    '[]'
),
(
    'EduTech Inovação',
    'Edtech com plataformas de ensino e capacitação. Conteúdos acessíveis e parcerias com escolas públicas.',
    'https://cdn.example.com/logos/edutech.png',
    77, 68, 88, 75,
    'Educação',
    0,
    'Datacenters com eficiência energética e PUE baixo',
    'Contratos de energia verde onde disponível',
    'Bolsas e inclusão para grupos sub-representados',
    'Remuneração competitiva e benefícios',
    'Transparência em métricas de impacto educacional',
    '[]'
),
(
    'MineraçãoResponsável',
    'Mineração com foco em rejeitos, recuperação de áreas e relações com comunidades. Metais e minerais industriais.',
    'https://cdn.example.com/logos/mineracaoresp.png',
    55, 50, 58, 57,
    'Mineração',
    0,
    'Plano de redução de emissões em elaboração',
    'Uso de fontes alternativas em algumas unidades',
    'Programas sociais nas regiões de operação',
    'Segurança e saúde ocupacional em evolução',
    'Relatório de sustentabilidade anual',
    '["Eventos ambientais em análise; plano de ação em curso"]'
),
(
    'TelecomVerde',
    'Operadora de telecomunicações. Eficiência energética em rede, reciclagem de equipamentos e inclusão digital.',
    'https://cdn.example.com/logos/telecomverde.png',
    70, 68, 72, 70,
    'Telecomunicações',
    0,
    'Meta de redução de consumo por TB transmitido',
    'Energia renovável em parte das estações',
    'Programa de conectividade em escolas e ONGs',
    'Política de diversidade e clima organizacional',
    'Indicadores de consumo e reciclagem divulgados',
    '[]'
),
(
    'CosméticosNaturais',
    'Indústria de cosméticos com ingredientes naturais e orgânicos. Embalagens recicláveis e refil.',
    'https://cdn.example.com/logos/cosmeticosnat.png',
    75, 76, 74, 75,
    'Cosméticos',
    0,
    'Carbon footprint da cadeia em redução',
    'Energia renovável e uso de água otimizado',
    'Não testes em animais; fornecedores auditados',
    'Condições de trabalho e segurança documentadas',
    'Lista de ingredientes e origem no site',
    '[]'
);
